### ISSUE TITLE
setId(299)

### ISSUE THREAD

**Issue by nickfl** [sanathp/DatabaseManager_For_Android#10]
On line <b>835</b> of AndroidDatabaseManager.java there is some id: <b>299</b> - what is it?

**Comment by sanathp** [comment]
its just some unique id for that view . As all the views are created dynamically , a unique id should be given every view for android to recognize them .

**Comment by nickfl** [comment]
Hi Sanath,

I know what <b>id</b> means, but somehow Android Studio does not :0!
I mean, it shows error at this line!?
I tried to change value, assign it to <b>int</b> and then pass to setId() - nothing worked.
At the end I just commented it, and the whole thing worked - Great job, BTW!!

Thanks,
Nick
