### ISSUE TITLE
Why don't use dbm.getData INSIDE the AndroidDatabaseManager class??? 

### ISSUE THREAD

**Issue by devgutt** [sanathp/DatabaseManager_For_Android#7]
In this case you don't need to change anything in SQLiteOpenHelper class at all. I only did this change in getData function:
```java
SQLiteDatabase sqlDB = dbm.getWritableDatabase();
```
and worked perfectly.

Maybe I am missing something?

Cool program by the way, very useful, thanks.

**Comment by sanathp** [comment]
getWritableDatabase will return null if its is called before onCreate .To handle that case its better to call getWritableDatabase from the class which creates the database , as the Constructor will have onCreate Command defined by user.

For More Info :
http://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#getWritableDatabase()

**Comment by devgutt** [comment]
AFAIK, the onCreate method will be called when you call getWritableDatabase for the first time (database creation). It will never return null.

**Comment by sanathp** [comment]
May be You are right . I will test and update if everything works fine. Thanks for the inputs
