### ISSUE TITLE
Blob

### ISSUE THREAD

**Issue by hpreslier** [sanathp/DatabaseManager_For_Android#8]
This was very helpful for me to see what was happening inside my database. However, the application crashes when I click on my database from inside your activity after I store a blob (in my case a byte array from bitmap) in the database.

**Comment by sanathp** [comment]
hi , 
I was treating everything as string . I did some changes at line 1142 to resolve the bug .

You can view the changes here https://github.com/sanathp/DatabaseManager_For_Android/commit/244cc36c55170725d7bcc1cf0a0ef1daa5960ae1

Please test now and let me know if its working fine.

**Comment by abdellahCode** [comment]
I have created a pull request for this.

**Comment by hpreslier** [comment]
Yes it works now. Thank you.
